// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrontEndE3.Models;

public partial class Categoria
{
    public int Id { get; set; }

    public string Nombre { get; set; }
}