// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrontEndE3.Models;

public partial class Usuario
{
    public string NombreUsuario { get; set; }

    public string Clave { get; set; }
}